[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"

[dev]
  command = "npm run start"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
